TILES_WIDTH = 44
TILES_HEIGHT = 44
TILE_SIZE = 16

SCREEN_WIDTH = TILES_WIDTH * TILE_SIZE
SCREEN_HEIGHT = TILES_HEIGHT * TILE_SIZE

FPS = 60

# UI
UI_FONT = 'graphics/fonts/Gamer.ttf'
UI_FONT_SIZE = 18

# Menu
TITLE_FONT_SIZE = 80
BUTTON_FONT_SIZE = 26 
COMPONENTS_GAP = 60